name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt@1.17'

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
        run: |
          ./gradlew sonarqube
